### ISSUE TITLE
Add an observation time to each sample. 

### ISSUE THREAD

**Issue by tnn1t1s** [leifwalsh/perfume#1]
this would allow users to see distribution as-of some time in the experiment, plot statistics over time, etc. 

to Leif's point, the observations are ordered so this is possible but I like the idea of having this in time semantics. for example, i could show that mean runtime over time, t, changed by X.

**Comment by leifwalsh** [comment]
As discussed, the observations actually made are the begin and end times for each sample, taken serially from each function benchmarked.  So for a given row, it's unclear which time to attach to a given row.

I understand the desire to plot over time, one doesn't necessarily want to plot with an x axis which is observation index, we might want to compare things in real time.

However, since python is single threaded (due to the GIL), `perfume` opts to run each function serially, not in parallel, to avoid any possible contention issues.  Therefore, for a given sample number, the start times will be different (the second function starts after the first one completes).

I think the best approach forward is to imagine one ran all the samples for a given function one after the other with nothing intervening, and basically do a cumulative sum of time spent in the function, per function benchmarked.  This would let you plot the samples on the same x axis and represent their times as if they had run concurrently on separate machines, but show results in human time.

To implement this, we could either provide a function that takes the samples as given and produces an indexed (by cumulative time) object, or lower level, simply return a dataframe which has both the begin and end times of every sample (without subtracting them to produce elapsed time), which is the lowest level information we can provide without dropping lower than `time.perf_counter()`.  Then one could subtract begin from end on their own to produce the elapsed times, and choose any of the begin or end times as the canonical time for a given observation.

What sounds best to you, @tnn1t1s?

**Comment by leifwalsh** [comment]
Added `perfume.analyze` and a way to plot I think what you want to see.  See this example:

 ![Cumulative Quantiles](https://github.com/leifwalsh/perfume/raw/master/docs/cumulative_quantiles.png)
